## Amazon RDS for MySQL Immersion day labs Template
## Infrastructure template for lab exercises
##
## Changelog:
## 2024-03-20 - create parameter group 
## Dependencies:
## none
##
## License:
## This sample code is made available under the MIT-0 license. See the LICENSE file.

AWSTemplateFormatVersion: 2010-09-09
Description: Amazon RDS for MySQL Immersion day labs

Resources:
# Create a random generated password and store it as a secret for the DB Instance
  RDSMySQLMasterSecret:
    Type: "AWS::SecretsManager::Secret"
    # checkov:skip=CKV_AWS_149:default secret policy is not needed
    Properties:
      KmsKeyId: alias/aws/secretsmanager
      Description: "Administrator user credentials for RDS MySQL ${AWS::StackName}-instances"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "administrator"}'
        GenerateStringKey: 'password'
        PasswordLength: 10
        ExcludeCharacters: '="@/\$`&:{}()[];'
      Tags:
        - Key: Name
          Value: !Join ['-', ['rds-database-secret', !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]


Outputs:
  InstanceParamsGRName:
    Description: 'param group name'
    Value: !Ref RDSMySQLMasterSecret
    Export:
      Name: !Sub '${AWS::StackName}-RDSMySQLMasterSecret'